jungletasks/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout 

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('tasks.views',

    url(r'^$', 'index', name='url_index'), 
    url(r'^about/$', 'about', name='url_about'), 

    url(r'^tasks/$', 'tasks', name='url_tasks'), 
    url(r'^tasks/inbox/$', 'tasks_inbox', name='url_tasks_inbox'), 
    url(r'^tasks/completed/$', 'tasks_completed', name='url_tasks_completed'), 
    url(r'^tasks/(?P<id>\d+)/$', 'tasks_by_label', name='url_tasks_label'), 

    url(r'^tasks/add/$', 'tasks_add_task', name='url_tasks_add'), 
    url(r'^tasks/edit/(?P<id>\d+)/$', 'tasks_edit', name='url_tasks_edit'), 
    url(r'^tasks/delete/(?P<id>\d+)/$', 'tasks_delete', name='url_tasks_delete'), 
    url(r'^tasks/mark/$', 'tasks_mark_done', name='url_tasks_mark_done'), 

    url(r'^label/$', 'label', name='url_label'), 
    url(r'^label/add/$', 'label_add', name='url_label_add'), 
    url(r'^label/edit/(?P<id>\d+)/$', 'label_edit', name='url_label_edit'), 
    url(r'^label/delete/(?P<id>\d+)/$', 'label_delete', name='url_label_delete'), 

    url(r'^label/assign/$', 'label_task_assign_json', name='url_task_assign_json'), 
    url(r'^label/hidden/$', 'label_set_hidden_json', name='url_label_set_hidden_json'), 

    # uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

# account 
urlpatterns += patterns('account.views',
    url(r'^accounts/login/$', 'login', name='url_login'), 
    url(r'^accounts/signup/$', 'register', name='url_signup'), 
    url(r'^accounts/confirm/$', 'confirm_email', name='url_email_confirmation'), 
    url(r'^accounts/password-change/$', 'password_change', name='url_password_change'), 
    url(r'^accounts/password-reset/$', 'password_reset', name='url_password_reset'), 
)

# import and export urls 
urlpatterns += patterns('tools.views',
    url(r'^tools/$', 'tools', name='url_tools'), 
    url(r'^tools/export/preview/all/$', 'tasks_export_preview_all', name='url_export_preview_all'), 
    url(r'^tools/export/preview/(?P<id>\d+)/$', 'tasks_export_preview_label', name='url_export_preview_label'), 
    url(r'^tools/export/$', 'tasks_export', name='url_export'), 
    
    url(r'^tools/log/$', 'activity_log', name='url_log'), 
)

# authentication 
urlpatterns += patterns('',
  # url(r'^accounts/signup/$', 'register', name='url_signup'), 
  #(r'^login/$',  login), 
  url(r'^logout/$', logout, name='url_logout', kwargs={ 'next_page': '/' }), 
)

# for dev
urlpatterns += patterns('dev.views',
  url(r'^dev/login/$', 'dev_login', name='url_dev_login' ), 
)

# urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jungletasks.views.home', name='home'),
    # url(r'^jungletasks/', include('jungletasks.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
# )

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class ActiveLabelManager(models.Manager):
  def get_query_set(self):
    """
    Returns only active labels
    """
    return super(ActiveLabelManager, self).get_query_set().filter(active=True)


class Label(models.Model):
  """
  A label
  """
  user = models.ForeignKey(User) 
  name = models.CharField(max_length=48,
                          help_text="No spaces, case-insensitive.")
  # auto_now_add is set when the object is created
  created = models.DateTimeField(auto_now_add=True)
  # auto_now is set when the object is saved
  edited = models.DateTimeField(auto_now=True)
  color = models.CharField(max_length=9, 
                           help_text="Hex code for color.", default='#ffff99')
  # true if the label should not be shown in the home view 
  hidden = models.BooleanField(default=False)
  # active if False if the label is deleted 
  active = models.BooleanField(default=True)

  # the default manager (only handling active labels)
  objects = ActiveLabelManager()
  # access to all labels 
  history = models.Manager()

  def num_tasks(self):
    """
    Returns the number of tasks that have this (unique) label
    """
    return Task.objects.filter(labels=self).count()

  def num_not_done_tasks(self):
    """
    Returns the number of tasks that have this (unique) label
    and are not done
    """
    return Task.objects.filter(labels=self, completed=False).count()  

class SmartLabel(Label):
  """
  A smart label
  """
  OPERATOR_CHOICES = (
        ('AND', 'Conjunction'),
        ('OR', 'Disjunction'),
  )
  labels = models.ManyToManyField(Label, related_name='labels')
  operator = models.CharField(max_length=3, choices=OPERATOR_CHOICES)


class SystemLabel(models.Model):
  """
  A system label
  """
  SYSTEM_LABELS = (
        ('UNLABELED', 'Unlabeled'),
        ('PRIORITY', 'Priority'),
  )
  label = models.CharField(max_length=24, choices=SYSTEM_LABELS)


class Task(models.Model):
  """
  A task 
  """
  PRIORITIES = (
        ('HIG', 'High'),
        ('NOR', 'Normal'),
  )

  user = models.ForeignKey(User) 

  task = models.CharField(max_length=1024, help_text="The task")
  notes = models.TextField(blank=True, null=True)
  completed = models.BooleanField(default=False)
  priority = models.CharField(max_length=3, choices=PRIORITIES, default='NOR')
  labels = models.ManyToManyField(Label)

  # auto_now_add is set when the object is created
  date_created = models.DateTimeField(auto_now_add=True)
  # auto_now is set when the object is saved
  date_edited = models.DateTimeField(auto_now=True)
  date_completed = models.DateTimeField(blank=True, null=True)
  # due date 
  date_due = models.DateTimeField(blank=True, null=True)

  class Meta:
    ordering = ('priority', 'date_due', '-date_edited')

  def __unicode__(self):
    return self.task

  def is_completed(self):
    """ returns True if the task is marked as completed, False otherwise """
    return self.completed

  def is_important(self):
    return self.priority == 'HIG'

  def label_ids(self):
    """ returns the IDs of the associated labels """
    return [l.id for l in self.labels.all()]
    
  def label_ids_str(self):
    """ returns a string with the label IDs space-separated """
    return ' '.join([str(l) for l in self.label_ids()])

tasks/forms.py
from django import forms

import models

class TaskForm(forms.ModelForm):
  """
  A form for adding a task 
  """
  class Meta:
    model = models.Task
    exclude = ['user', 'completed', 'date_due', 'date_completed', 'labels']
    widgets = {
      'task': forms.TextInput(attrs={'class': 'form-control special-form-control', 'placeholder': 'Task'}),
      'notes': forms.Textarea(attrs={'class': 'form-control special-form-control', 'placeholder': 'Notes', 'rows': 10}),
      'priority': forms.Select(attrs={'class': 'form-control special-form-control'}),
    }
    
  def clean_task(self):
    task = self.cleaned_data.get('task', '')
    if task == '':
      raise forms.ValidationError(_('The task cannot be empty'))
    return task
    

tasks/views.py
from django.template import RequestContext 
from django.shortcuts import render_to_response, redirect 

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.http import HttpResponse, HttpResponseRedirect, Http404

from django.views.decorators.http import require_http_methods, require_GET, require_POST

from django.core.urlresolvers import reverse
from django.core import serializers
from django.utils import simplejson
from datetime import datetime

from django.core.paginator import Paginator, InvalidPage, EmptyPage

from tasks.models import Task, Label, SystemLabel

from tasks.forms import TaskForm

import account.models as a_models

@require_GET
def index(request): 
  """
  Home page
  """
  if request.user.is_authenticated():
    if not 'hp' in request.GET:
      return redirect('url_tasks_inbox')
  
  return render_to_response('index.html', {}, 
                  context_instance=RequestContext(request)) 


@login_required
@require_GET
def tasks(request):
  """
  Re-directs to the tasks in the 'inbox'
  """
  return redirect('url_tasks_inbox')  


@login_required
@require_http_methods(['GET', 'POST'])
def tasks_inbox(request):
  """
  Display tasks in the 'inbox'
  """
  tasks = Task.objects.filter(user=request.user, completed=False)
  return tasks_display(request, tasks)


@login_required
@require_GET
def tasks_completed(request):
  """
  Display completed tasks 
  """
  tasks = Task.objects.filter(user=request.user, completed=True).order_by('-date_completed')
  return tasks_display(request, tasks)


@login_required
@require_GET
def tasks_by_label(request, id):
  """
  Display tasks by a label
  """
  try:
    label = Label.objects.get(id=id)
    tasks = Task.objects.filter(user=request.user, labels=label, completed=False)
    return tasks_display(request, tasks, label)
  except Label.DoesNotExist:
    raise Http404


def tasks_display(request, tasks, label=None):
  """
  Utility method for displaying the given tasks 
  """
  # all the users labels
  labels = Label.objects.filter(user=request.user, hidden=False, active=True)
  # the number of tasks not done (used to display 'inbox' count)
  num_tasks_not_done = Task.objects.filter(user=request.user, completed=False).count()
  # paginate the tasks 
  paginator = Paginator(tasks, 10) 
  # make sure page request is an int. If not, deliver first page.
  try:
    page = int(request.GET.get('page', '1'))
  except ValueError:
    page = 1
  # if page request (9999) is out of range, deliver last page of results.
  try:
    paged_items = paginator.page(page)
  except (EmptyPage, InvalidPage):
    paged_items = paginator.page(paginator.num_pages)
  
  return render_to_response('tasks/index.html', 
                            { 'tasks': paged_items, 
                              'active_label': label, 
                              'labels': labels, 
                              'num_tasks_not_done': num_tasks_not_done }, 
                  context_instance=RequestContext(request)) 


@login_required
@require_POST
def tasks_add_task(request):
  """ Adds a new task """
  if 'task' in request.POST:
    task = request.POST.get('task') or ''
    if task != '': 
      # create task
      task = Task(user=request.user, task=task)
      task.save()
      # add label
      if 'active_label' in request.POST:
        l_id = request.POST.get('active_label')
        try:
          label = Label.objects.get(id=l_id)
          task.labels.add(label)
          return redirect('url_tasks_label', id=l_id)
        except Label.DoesNotExist:
          pass
    else:
      messages.error(request, 'A task cannot be empty')

  return redirect('url_tasks_inbox')


@login_required
@require_http_methods(['GET', 'POST'])
def tasks_edit(request, id):
  """
  Edit a task 
  """
  try:
    
    task = Task.objects.get(user=request.user, id=id)
    
    if request.method == 'POST':
      form = TaskForm(request.POST) 
      if form.is_valid(): 
        # update task 
        data = form.cleaned_data
        task.task = data.get('task')
        task.notes = data.get('notes')
        task.priority = data.get('priority')
        task.save()
        # set message 
        messages.add_message(request, messages.SUCCESS, 'Task updated')
        return redirect('url_tasks')
    else:
      form = TaskForm(instance=task)

    return render_to_response('tasks/edit.html', 
                              { 'task': task, 
                                'form' : form }, 
                    context_instance=RequestContext(request)) 
    
  except Task.DoesNotExist:
    pass
    
  raise Http404


@login_required
@require_POST
def tasks_delete(request, id):
  """
  Delete a task 
  """
  try:
    task = Task.objects.get(user=request.user, id=id)
    task.delete()
    messages.add_message(request, messages.SUCCESS, 'The task was deleted')
  except Label.DoesNotExist:
    messages.add_message(request, messages.ERROR, 'An error occurred, the task could not be deleted')
      
  return redirect('url_tasks')


@login_required
@require_POST
def tasks_mark_done(request):
  """
  Marks a task done (or not done)
  """
  t_id = request.POST['task']
  action = request.POST['action']
  
  # default 
  json = simplejson.dumps({ 'status': 'KO' })
  
  if t_id != None and action != None:
    try: 
      task = Task.objects.get(user=request.user, id=t_id)
      if action == 'done':
        task.completed = True
        task.date_completed = datetime.now()
      elif action == 'undone':
        task.completed = False
        task.date_completed = None
      task.save()
      json = simplejson.dumps({ 'status': 'OK' })
    except Task.DoesNotExist, Label.DoesNotExist: 
      json = simplejson.dumps({ 
        'status': 'KO', 
        'message': 'An error occurred, the task could not be updated' 
      })
      
  return HttpResponse(json, mimetype = 'application/json', 
                      content_type = 'application/json; charset=utf8')


@login_required
@require_GET
def label(request):
  """
  A view to create, delete and modify labels (categories)
  """
  
  labels = Label.objects.filter(user=request.user)

  try:
    profile = request.user.get_profile()
    system_labels = profile.system_labels.all()
  except a_models.UserProfile.DoesNotExist:
    system_labels = None

  return render_to_response('label/index.html', 
                            { 'labels' : labels,
                              'system_labels' : system_labels }, 
                  context_instance=RequestContext(request)) 


@login_required
@require_POST
def label_add(request):
  """
  Add a label
  """
  if 'label' in request.POST:
    label = request.POST['label'].strip()
    
    if label == '':
      messages.add_message(request, messages.ERROR, 'The label cannot be empty')
    else:
      # check that the label name does not already exist
      try:
        Label.objects.get(user=request.user, name__iexact=label)
        messages.add_message(request, messages.ERROR, 'The label already exists (labels are case-insensitive)')
      except Label.DoesNotExist:
        label = Label(user=request.user, name=label)
        label.save()
        messages.add_message(request, messages.SUCCESS, 'The label was created')
      
  return HttpResponseRedirect(reverse('url_label'))
  
  
@login_required
@require_http_methods(['GET', 'POST'])
def label_edit(request, id):
  """
  Edit a label
  """
  try: 
    label = Label.objects.get(user=request.user, id=id)
    
    if request.method == 'POST':
      l = request.POST.get('label') or ''
      l = l.strip()
      # check for empty labels 
      if l == '':
          messages.add_message(request, messages.ERROR, 'The label cannot be empty')
      else:
        # check for existing labels
        ls = Label.objects.filter(user=request.user, name__iexact=l).exclude(id=id)
        if len(ls) > 0:
          messages.add_message(request, messages.ERROR, 'That label already exists (labels are case-insensitive)')
        else:
          # TODO: should catch error if the label is too long, for example. 
          label.name = l
          # color
          label.color = request.POST.get('color') or '#ffff99'
          label.save()
          messages.add_message(request, messages.SUCCESS, 'The label was updated')
          return redirect('url_label')
          
    return render_to_response('label/edit.html', 
                              { 'label' : label }, 
                    context_instance=RequestContext(request)) 
  except:
    raise Http404


@login_required
@require_POST
def label_delete(request, id):
  """
  Delete a label (actually, just marks it as inactive)
  """
  try:
    label = Label.objects.get(user=request.user, id=id)
    label.active = False
    label.save()
    messages.add_message(request, messages.SUCCESS, 'The label was deleted')
  except Label.DoesNotExist:
    messages.add_message(request, messages.ERROR, 'An error occurred, the label could not be deleted')
      
  return redirect('url_label')


@login_required
@require_POST
def label_task_assign_json(request):
  """
  Assigns a label to a task
  """
  t_id = request.POST['task']
  l_id = request.POST['label']
  action = request.POST['action']
  
  # default 
  json = simplejson.dumps({ 'status': 'KO' })
  
  if t_id != None and l_id != None and action != None:
    try: 
      # assign label to task 
      task = Task.objects.get(user=request.user, id=t_id)
      label = Label.objects.get(user=request.user, id=l_id)
      if action == 'add':
        task.labels.add(label)
      elif action == 'remove':
        label.task_set.remove(task)
      json = simplejson.dumps({ 'status': 'OK' })
    except Task.DoesNotExist, Label.DoesNotExist: 
      json = simplejson.dumps({ 
        'status': 'KO', 
        'message': 'An error occurred, the task could not be updated' 
      })
      
  return HttpResponse(json, mimetype = 'application/json', 

tasks/templates/label/add.html
{% extends "base.html" %}

{% block stylesheet %}
    {# <link href="/static/css/main.css" rel="stylesheet" type="text/css" /> #}
    {# <link href="/static/css/forms.css" rel="stylesheet" type="text/css" /> #}
{% endblock %}

{% block script %}
{# <script type="text/javascript" src="/static/js/tasks.js"></script> #}
{% endblock %}

{% block js-on-document-load %}

/* focus on task text */
$("#label").focus();

{% endblock %}

{% block contents %}

{% block page_header %}
<h1>Add Label</h1>
{% endblock %}

<form action="" method="post" role="form">{% csrf_token %}

    <fieldset>
      <div class="form-group">
        <label for="label">Label</label>
        <input id="label" name="label" type="text" placeholder="Label">
      </div>
      <button type="submit" class="btn btn-primary">Add</button>
    </fieldset>

</form>

{% endblock %}

tasks/templates/label/edit.html
{% extends "base.html" %}

{% block stylesheet %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/spectrum.css" />
{% endblock stylesheet %}

{% block script %}
<script type="text/javascript" src="{{ STATIC_URL }}js/spectrum.js"></script>

<script id="label-delete-confirm-template" type="text/x-handlebars-template">
{% verbatim %}
<form action="/label/delete/{{id}}/" method="POST">
{% endverbatim %}
{% csrf_token %}
{% verbatim %}
<input type="submit" class="btn btn-danger btn-confirm btn-delete-confirm" value="Are you sure?" />
<button type="button" class="btn btn-default btn-confirm btn-delete-cancel">No</button>
</form>
{% endverbatim %}
</script>

<script type="text/javascript">
<!--
$(function() {
  /* focus on label text */
  setInterval(function() {
      $("#label").focus();
  }, 200);

  $(".btn-delete").click(function() {
      // hide the button just clicked 
      $(this).hide();

      // create the form to delete the label 
      var id = $(this).data('id');
      var source = $("#label-delete-confirm-template").html();
      var template = Handlebars.compile(source);
      var html = template({id: id});
      $(this).after(html);
    
      // register the cancel event 
      $('.btn-delete-cancel').click(function(e) {
          // remove the confirmation set of buttons 
          $(".btn-confirm").remove();
          // bring back the original button
         $(".btn-delete").show(); 
         e.stopPropagation();
      });
  }); 
  
  $("#colorpicker").spectrum({
    color: '{{ label.color }}', 
    flat: true, 
    showButtons: false, 
    move: function(color) {
      var color = color.toHexString();
      $("#label-color").attr('value', color);
      $("ul.labels li").css('background-color', color);
    }
  })
});
-->
</script>
{% endblock script %}

{% block contents %}

<p><a href="{% url 'url_label' %}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-chevron-left"></span> Back to labels</a></p>

<h1>Edit Label</h1>

<form action="" method="POST" role="form" class="">{% csrf_token %}
    <fieldset>
      <div class="form-group">
        <label for="label">Label</label>
        <input id="label" name="label" type="text" placeholder="Label" value="{{ label.name }}" class="form-control special-form-control"></input>
      </div>
      <div class="form-group">
        <label for="colorpicker">Color</label>
        <div class="clearfix"></div>
        <input type="text" id="colorpicker" class="clearfix" />
        <div class="clearfix"></div>
        <label for="colorpicker">Preview</label>
        <ul class="labels">
          <li style="background-color: {{ label.color }}; width: 172px;">&nbsp;</li>
        </ul>
        
      </div>
      <input id="label-color" type="hidden" name="color" value="#ffff99" />
      <button type="submit" class="btn btn-primary">Update</button>
      <div class="pull-right">
        <button type="button" class="btn btn-danger btn-delete" data-id="{{ label.id }}">Delete label</button>
      </div>
    </fieldset>
</form>

<p></p>



{% endblock contents %}

tasks/templates/label/index.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
<!--
$(function() {
    setInterval(function() {
        $("#inputLabel").focus();
    }, 200);
});

function Label() {
    
    if (!(this instanceof Label)) {
        return new Label();
    }
    
    this.setLabelHiddenStatus = function(id, hidden, callback) {
        $.post("{% url 'url_label_set_hidden_json' %}", {
                'id': id,
                'hidden': hidden ? 'true' : 'false'
            },
            function(data, status) {
                if (status == 'success' && data.status == 'OK') {
                    callback();
                }
            }
        );
    };
}

var label = new Label();

// listening to changing the 'hidden' status of a label 
$(".btn-hidden-toggle").click(function() {
    var id = $(this).data('id'), 
        hidden = $(this).data('hidden') == 'True', 
        btn = $(this);
    label.setLabelHiddenStatus(id, !hidden, function() {
        // updates the DOM if the change was successful 
        var icon = btn.find('span.glyphicon'), 
            gopen = 'glyphicon-eye-open', 
            gclose = 'glyphicon-eye-close';
        if (hidden) {
          btn.addClass('btn-success').removeClass('btn-danger');
          btn.data('hidden', 'False');
          icon.addClass(gopen).removeClass(gclose); 
        } else {
          btn.addClass('btn-danger').removeClass('btn-success');
          btn.data('hidden', 'True');
          icon.addClass(gclose).removeClass(gopen);
        }
    });
});

-->
</script>
{% endblock script %}

{% block contents %}
<h1>Your labels</h1>

<form role="form" action="{% url 'url_label_add' %}" method="POST">{% csrf_token %}
    <div class="row">
        <div class="col-sm-9">
            <label class="sr-only" for="inputLabel">Label</label>
            <input type="text" class="form-control" id="inputLabel" name="label" placeholder="Label">
        </div>
        <div class="col-sm-3">
            <button type="submit" class="btn btn-default form-control">
              &plus; add label</button>
        </div>
    </div>
</form>

<p></p>
    
{% if labels %}
<table class="table table-labels">
    <thead>
        <tr class="">
            <th>Label</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for label in labels %}
        {% url 'url_tasks_label' label.id as url_label %}
        <tr style="background-color: {{ label.color }}">
            <td>
              <a class="label-link" href="{{ url_label }}">{{ label.name }}</a>
              (<strong>{{ label.num_not_done_tasks}}</strong>)
            </td>
            <td>
                <button type="button" data-id="{{ label.id }}" data-hidden="{{ label.hidden }}" class="btn btn-sm btn-{% if label.hidden %}danger{% else %}success{% endif %} btn-hidden-toggle" title="Toggle visibility">
                  {% if label.hidden %}
                  <span class="glyphicon glyphicon-eye-close"></span></button>
                  {% else %}
                  <span class="glyphicon glyphicon-eye-open"></span></button>
                  {% endif %}
                  
                <a href="{% url 'url_label_edit' label.id %}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-edit"></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <p><strong>There are no labels here.</strong></p>
    <p><em>Try adding a label first.</em></p>
{% endif %}

{# {% if system_labels %} #}
{# <h1>System labels</h1> #}
{# {% for label in system_labels %} #}
{# {{ label.get_label_display }}  #}
{# {% endfor %} #}
{# {% endif %} #}

{% endblock %}