jungletasks/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout 

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('tasks.views',

    url(r'^$', 'index', name='url_index'), 
    url(r'^about/$', 'about', name='url_about'), 

    url(r'^tasks/$', 'tasks', name='url_tasks'), 
    url(r'^tasks/inbox/$', 'tasks_inbox', name='url_tasks_inbox'), 
    url(r'^tasks/completed/$', 'tasks_completed', name='url_tasks_completed'), 
    url(r'^tasks/(?P<id>\d+)/$', 'tasks_by_label', name='url_tasks_label'), 

    url(r'^tasks/add/$', 'tasks_add_task', name='url_tasks_add'), 
    url(r'^tasks/edit/(?P<id>\d+)/$', 'tasks_edit', name='url_tasks_edit'), 
    url(r'^tasks/delete/(?P<id>\d+)/$', 'tasks_delete', name='url_tasks_delete'), 
    url(r'^tasks/mark/$', 'tasks_mark_done', name='url_tasks_mark_done'), 

    url(r'^label/$', 'label', name='url_label'), 
    url(r'^label/add/$', 'label_add', name='url_label_add'), 
    url(r'^label/edit/(?P<id>\d+)/$', 'label_edit', name='url_label_edit'), 
    url(r'^label/delete/(?P<id>\d+)/$', 'label_delete', name='url_label_delete'), 

    url(r'^label/assign/$', 'label_task_assign_json', name='url_task_assign_json'), 
    url(r'^label/hidden/$', 'label_set_hidden_json', name='url_label_set_hidden_json'), 

    # uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

# account 
urlpatterns += patterns('account.views',
    url(r'^accounts/login/$', 'login', name='url_login'), 
    url(r'^accounts/signup/$', 'register', name='url_signup'), 
    url(r'^accounts/confirm/$', 'confirm_email', name='url_email_confirmation'), 
    url(r'^accounts/password-change/$', 'password_change', name='url_password_change'), 
    url(r'^accounts/password-reset/$', 'password_reset', name='url_password_reset'), 
)

# import and export urls 
urlpatterns += patterns('tools.views',
    url(r'^tools/$', 'tools', name='url_tools'), 
    url(r'^tools/export/preview/all/$', 'tasks_export_preview_all', name='url_export_preview_all'), 
    url(r'^tools/export/preview/(?P<id>\d+)/$', 'tasks_export_preview_label', name='url_export_preview_label'), 
    url(r'^tools/export/$', 'tasks_export', name='url_export'), 
    
    url(r'^tools/log/$', 'activity_log', name='url_log'), 
)

# authentication 
urlpatterns += patterns('',
  # url(r'^accounts/signup/$', 'register', name='url_signup'), 
  #(r'^login/$',  login), 
  url(r'^logout/$', logout, name='url_logout', kwargs={ 'next_page': '/' }), 
)

# for dev
urlpatterns += patterns('dev.views',
  url(r'^dev/login/$', 'dev_login', name='url_dev_login' ), 
)

# urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jungletasks.views.home', name='home'),
    # url(r'^jungletasks/', include('jungletasks.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
# )

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class ActiveLabelManager(models.Manager):
  def get_query_set(self):
    """
    Returns only active labels
    """
    return super(ActiveLabelManager, self).get_query_set().filter(active=True)


class Label(models.Model):
  """
  A label
  """
  user = models.ForeignKey(User) 
  name = models.CharField(max_length=48,
                          help_text="No spaces, case-insensitive.")
  # auto_now_add is set when the object is created
  created = models.DateTimeField(auto_now_add=True)
  # auto_now is set when the object is saved
  edited = models.DateTimeField(auto_now=True)
  color = models.CharField(max_length=9, 
                           help_text="Hex code for color.", default='#ffff99')
  # true if the label should not be shown in the home view 
  hidden = models.BooleanField(default=False)
  # active if False if the label is deleted 
  active = models.BooleanField(default=True)

  # the default manager (only handling active labels)
  objects = ActiveLabelManager()
  # access to all labels 
  history = models.Manager()

  def num_tasks(self):
    """
    Returns the number of tasks that have this (unique) label
    """
    return Task.objects.filter(labels=self).count()

  def num_not_done_tasks(self):
    """
    Returns the number of tasks that have this (unique) label
    and are not done
    """
    return Task.objects.filter(labels=self, completed=False).count()  

class SmartLabel(Label):
  """
  A smart label
  """
  OPERATOR_CHOICES = (
        ('AND', 'Conjunction'),
        ('OR', 'Disjunction'),
  )
  labels = models.ManyToManyField(Label, related_name='labels')
  operator = models.CharField(max_length=3, choices=OPERATOR_CHOICES)


class SystemLabel(models.Model):
  """
  A system label
  """
  SYSTEM_LABELS = (
        ('UNLABELED', 'Unlabeled'),
        ('PRIORITY', 'Priority'),
  )
  label = models.CharField(max_length=24, choices=SYSTEM_LABELS)


class Task(models.Model):
  """
  A task 
  """
  PRIORITIES = (
        ('HIG', 'High'),
        ('NOR', 'Normal'),
  )

  user = models.ForeignKey(User) 

  task = models.CharField(max_length=1024, help_text="The task")
  notes = models.TextField(blank=True, null=True)
  completed = models.BooleanField(default=False)
  priority = models.CharField(max_length=3, choices=PRIORITIES, default='NOR')
  labels = models.ManyToManyField(Label)

  # auto_now_add is set when the object is created
  date_created = models.DateTimeField(auto_now_add=True)
  # auto_now is set when the object is saved
  date_edited = models.DateTimeField(auto_now=True)
  date_completed = models.DateTimeField(blank=True, null=True)
  # due date 
  date_due = models.DateTimeField(blank=True, null=True)

  class Meta:
    ordering = ('priority', 'date_due', '-date_edited')

  def __unicode__(self):
    return self.task

  def is_completed(self):
    """ returns True if the task is marked as completed, False otherwise """
    return self.completed

  def is_important(self):
    return self.priority == 'HIG'

  def label_ids(self):
    """ returns the IDs of the associated labels """
    return [l.id for l in self.labels.all()]
    
  def label_ids_str(self):
    """ returns a string with the label IDs space-separated """
    return ' '.join([str(l) for l in self.label_ids()])

tasks/forms.py
from django import forms

import models

class TaskForm(forms.ModelForm):
  """
  A form for adding a task 
  """
  class Meta:
    model = models.Task
    exclude = ['user', 'completed', 'date_due', 'date_completed', 'labels']
    widgets = {
      'task': forms.TextInput(attrs={'class': 'form-control special-form-control', 'placeholder': 'Task'}),
      'notes': forms.Textarea(attrs={'class': 'form-control special-form-control', 'placeholder': 'Notes', 'rows': 10}),
      'priority': forms.Select(attrs={'class': 'form-control special-form-control'}),
    }
    
  def clean_task(self):
    task = self.cleaned_data.get('task', '')
    if task == '':
      raise forms.ValidationError(_('The task cannot be empty'))
    return task
    

tasks/views.py
from django.template import RequestContext 
from django.shortcuts import render_to_response, redirect 

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.http import HttpResponse, HttpResponseRedirect, Http404

from django.views.decorators.http import require_http_methods, require_GET, require_POST

from django.core.urlresolvers import reverse
from django.core import serializers
from django.utils import simplejson
from datetime import datetime

from django.core.paginator import Paginator, InvalidPage, EmptyPage

from tasks.models import Task, Label, SystemLabel

from tasks.forms import TaskForm

import account.models as a_models

@require_GET
def index(request): 
  """
  Home page
  """
  if request.user.is_authenticated():
    if not 'hp' in request.GET:
      return redirect('url_tasks_inbox')
  
  return render_to_response('index.html', {}, 
                  context_instance=RequestContext(request)) 


@login_required
@require_GET
def tasks(request):
  """
  Re-directs to the tasks in the 'inbox'
  """
  return redirect('url_tasks_inbox')  


@login_required
@require_http_methods(['GET', 'POST'])
def tasks_inbox(request):
  """
  Display tasks in the 'inbox'
  """
  tasks = Task.objects.filter(user=request.user, completed=False)
  return tasks_display(request, tasks)


@login_required
@require_GET
def tasks_completed(request):
  """
  Display completed tasks 
  """
  tasks = Task.objects.filter(user=request.user, completed=True).order_by('-date_completed')
  return tasks_display(request, tasks)


@login_required
@require_GET
def tasks_by_label(request, id):
  """
  Display tasks by a label
  """
  try:
    label = Label.objects.get(id=id)
    tasks = Task.objects.filter(user=request.user, labels=label, completed=False)
    return tasks_display(request, tasks, label)
  except Label.DoesNotExist:
    raise Http404


def tasks_display(request, tasks, label=None):
  """
  Utility method for displaying the given tasks 
  """
  # all the users labels
  labels = Label.objects.filter(user=request.user, hidden=False, active=True)
  # the number of tasks not done (used to display 'inbox' count)
  num_tasks_not_done = Task.objects.filter(user=request.user, completed=False).count()
  # paginate the tasks 
  paginator = Paginator(tasks, 10) 
  # make sure page request is an int. If not, deliver first page.
  try:
    page = int(request.GET.get('page', '1'))
  except ValueError:
    page = 1
  # if page request (9999) is out of range, deliver last page of results.
  try:
    paged_items = paginator.page(page)
  except (EmptyPage, InvalidPage):
    paged_items = paginator.page(paginator.num_pages)
  
  return render_to_response('tasks/index.html', 
                            { 'tasks': paged_items, 
                              'active_label': label, 
                              'labels': labels, 
                              'num_tasks_not_done': num_tasks_not_done }, 
                  context_instance=RequestContext(request)) 


@login_required
@require_POST
def tasks_add_task(request):
  """ Adds a new task """
  if 'task' in request.POST:
    task = request.POST.get('task') or ''
    if task != '': 
      # create task
      task = Task(user=request.user, task=task)
      task.save()
      # add label
      if 'active_label' in request.POST:
        l_id = request.POST.get('active_label')
        try:
          label = Label.objects.get(id=l_id)
          task.labels.add(label)
          return redirect('url_tasks_label', id=l_id)
        except Label.DoesNotExist:
          pass
    else:
      messages.error(request, 'A task cannot be empty')

  return redirect('url_tasks_inbox')


@login_required
@require_http_methods(['GET', 'POST'])
def tasks_edit(request, id):
  """
  Edit a task 
  """
  try:
    
    task = Task.objects.get(user=request.user, id=id)
    
    if request.method == 'POST':
      form = TaskForm(request.POST) 
      if form.is_valid(): 
        # update task 
        data = form.cleaned_data
        task.task = data.get('task')
        task.notes = data.get('notes')
        task.priority = data.get('priority')
        task.save()
        # set message 
        messages.add_message(request, messages.SUCCESS, 'Task updated')
        return redirect('url_tasks')
    else:
      form = TaskForm(instance=task)

    return render_to_response('tasks/edit.html', 
                              { 'task': task, 
                                'form' : form }, 
                    context_instance=RequestContext(request)) 
    
  except Task.DoesNotExist:
    pass
    
  raise Http404


@login_required
@require_POST
def tasks_delete(request, id):
  """
  Delete a task 
  """
  try:
    task = Task.objects.get(user=request.user, id=id)
    task.delete()
    messages.add_message(request, messages.SUCCESS, 'The task was deleted')
  except Label.DoesNotExist:
    messages.add_message(request, messages.ERROR, 'An error occurred, the task could not be deleted')
      
  return redirect('url_tasks')


@login_required
@require_POST
def tasks_mark_done(request):
  """
  Marks a task done (or not done)
  """
  t_id = request.POST['task']
  action = request.POST['action']
  
  # default 
  json = simplejson.dumps({ 'status': 'KO' })
  
  if t_id != None and action != None:
    try: 
      task = Task.objects.get(user=request.user, id=t_id)
      if action == 'done':
        task.completed = True
        task.date_completed = datetime.now()
      elif action == 'undone':
        task.completed = False
        task.date_completed = None
      task.save()
      json = simplejson.dumps({ 'status': 'OK' })
    except Task.DoesNotExist, Label.DoesNotExist: 
      json = simplejson.dumps({ 
        'status': 'KO', 
        'message': 'An error occurred, the task could not be updated' 
      })
      
  return HttpResponse(json, mimetype = 'application/json', 
                      content_type = 'application/json; charset=utf8')


@login_required
@require_GET
def label(request):
  """
  A view to create, delete and modify labels (categories)
  """
  
  labels = Label.objects.filter(user=request.user)

  try:
    profile = request.user.get_profile()
    system_labels = profile.system_labels.all()
  except a_models.UserProfile.DoesNotExist:
    system_labels = None

  return render_to_response('label/index.html', 
                            { 'labels' : labels,
                              'system_labels' : system_labels }, 
                  context_instance=RequestContext(request)) 


@login_required
@require_POST
def label_add(request):
  """
  Add a label
  """
  if 'label' in request.POST:
    label = request.POST['label'].strip()
    
    if label == '':
      messages.add_message(request, messages.ERROR, 'The label cannot be empty')
    else:
      # check that the label name does not already exist
      try:
        Label.objects.get(user=request.user, name__iexact=label)
        messages.add_message(request, messages.ERROR, 'The label already exists (labels are case-insensitive)')
      except Label.DoesNotExist:
        label = Label(user=request.user, name=label)
        label.save()
        messages.add_message(request, messages.SUCCESS, 'The label was created')
      
  return HttpResponseRedirect(reverse('url_label'))
  
  
@login_required
@require_http_methods(['GET', 'POST'])
def label_edit(request, id):
  """
  Edit a label
  """
  try: 
    label = Label.objects.get(user=request.user, id=id)
    
    if request.method == 'POST':
      l = request.POST.get('label') or ''
      l = l.strip()
      # check for empty labels 
      if l == '':
          messages.add_message(request, messages.ERROR, 'The label cannot be empty')
      else:
        # check for existing labels
        ls = Label.objects.filter(user=request.user, name__iexact=l).exclude(id=id)
        if len(ls) > 0:
          messages.add_message(request, messages.ERROR, 'That label already exists (labels are case-insensitive)')
        else:
          # TODO: should catch error if the label is too long, for example. 
          label.name = l
          # color
          label.color = request.POST.get('color') or '#ffff99'
          label.save()
          messages.add_message(request, messages.SUCCESS, 'The label was updated')
          return redirect('url_label')
          
    return render_to_response('label/edit.html', 
                              { 'label' : label }, 
                    context_instance=RequestContext(request)) 
  except:
    raise Http404


@login_required
@require_POST
def label_delete(request, id):
  """
  Delete a label (actually, just marks it as inactive)
  """
  try:
    label = Label.objects.get(user=request.user, id=id)
    label.active = False
    label.save()
    messages.add_message(request, messages.SUCCESS, 'The label was deleted')
  except Label.DoesNotExist:
    messages.add_message(request, messages.ERROR, 'An error occurred, the label could not be deleted')
      
  return redirect('url_label')


@login_required
@require_POST
def label_task_assign_json(request):
  """
  Assigns a label to a task
  """
  t_id = request.POST['task']
  l_id = request.POST['label']
  action = request.POST['action']
  
  # default 
  json = simplejson.dumps({ 'status': 'KO' })
  
  if t_id != None and l_id != None and action != None:
    try: 
      # assign label to task 
      task = Task.objects.get(user=request.user, id=t_id)
      label = Label.objects.get(user=request.user, id=l_id)
      if action == 'add':
        task.labels.add(label)
      elif action == 'remove':
        label.task_set.remove(task)
      json = simplejson.dumps({ 'status': 'OK' })
    except Task.DoesNotExist, Label.DoesNotExist: 
      json = simplejson.dumps({ 
        'status': 'KO', 
        'message': 'An error occurred, the task could not be updated' 
      })
      
  return HttpResponse(json, mimetype = 'application/json', 

tasks/templates/tasks/about.html
{% extends "base.html" %}

{% block contents %}

<h1>About</h1>

<p>
  This is a simple Web application for managing tasks built by <a href="http://metajungle.net">Jakob Henriksson</a>.
</p>

<p>
  The <a href="https://github.com/metajungle/jungletasks">source code can be found on GitHub</a>.
</p>

<h1>Frequently Asked Questions*</h1>

<h3>What's the point of this site?</h3>

<p>
  The site provides a very simple way of keeping track of tasks.
</p>

<h3>Seriously, what's the point?</h3>

<p>
  Ah, you mean, what's the <em>point</em>? In the sense that there are probably a thousand other web applications or desktop applications that do a better job?
</p>

<p>
  Well, in that case there is no point. You should use whatever system
  you find useful for your purposes. If the best way for you keep
  track of what you <em>need to get done</em> is to keep a simple text
  file on your computer with your tasks, you should probably do
  that. If you already have an application that you are happy with
  that helps you <em>get things done</em>, you should probably stick
  with that.
</p>

<h3>What is a good workflow for managing tasks?</h3>

<p>Whatever works for you.</p>

<p>
  Personally I like to organize everything
  around <em>labels</em>. Labels are just bins
  that you can put your tasks in. I typically have a general label for
  each project, let's call one such label <em>Project</em>. I put
  everything that has to do that particular project there. Then I keep
  other labels, e.g. <em>Issues</em> (or <em>Bugs</em>), <em>Todo
  Next</em>, <em>RC</em> (for release candidate), <em>Showstoppers</em>. I
  then organize all my tasks around these labels. I can move tasks
  around as I see fit. But everything is organized around these
  labels, but most importantly, their <em>names</em> is what keeps
  things moving forward. 
</p>

<h3>Isn't this site too simple?</h3>

<p>
  You mean it lacks a lot of features that are available in most
  other <a href="http://en.wikipedia.org/wiki/Issue_tracking_system">issue
  trackers</a>? Yes, it is true. However, I have found many issue
  trackers just overly complex. I don't need most of that stuff. 
</p>

<h3>What are some things I should be aware of when using the site?</h3>

<p>
  Labels are first-class entities and not simply text strings that are
  associated with tasks. This means that if you delete a label, that
  label is gone. Yes, from all the tasks that previously had that
  label. Same thing if you rename a label, that old name is gone. 
</p>

<p>
  Does it have to be this way? No, but that's the way it has been
  implemented. The tasks you have completed is of some interests once
  you have completed them. That's why completed tasks are still viewable. 
  They are also included if you export
  tasks. However, the labels are not stored in this way. They are just
  meant to help you organize your current tasks so that you know what
  needs to get done. They are your current window into your tasks. As
  you move forward that window will change (you will
  create/delete/rename labels). You old 'view' will not be saved. How
  you viewed things before is of less interest now. Your current label
  setup should be optimized to move things forward and get things
  done, <em>now</em>.
</p>

<h3>How do I mark a task as completed?</h3>

<p>
  You simply click on the task text. One click marks it as completed,
  another click returns it to being not completed.
</p>

<h3>How do I delete a task?</h3>

<p>
  You edit the task and delete the task from there.
</p>

<h3>How do I mark a task as high priority?</h3>

<p>
  You edit the task and select the priority level from there. 
</p>

<h3>Can I export my tasks so I can use them in other systems?</h3>

<p>
  Yes. In any view that has a task you can click 'export' from the main menu. 
  You will see a preview of a few tasks that shows how
  the exported tasks will be formatted. The actual export will contain
  all tasks in the view you were in when you clicked 'export'. If you
  want to export all tasks, click the "All" label first and then
  'export' in the top-right corner. After previewing you can then export
  your tasks. A file will be saved to your local disk with all the tasks. 
</p>

<p>
  The format of the export
  is <a href="http://orgmode.org">Org-Mode</a>. It's basically a text
  file so you can do whatever you want with it.
</p>

<h3>How can I reset my password?</h3>

<p>
  You can <a href="{% url 'url_password_reset' %}">reset your password here</a>.
</p>

<h3>Will you support other features in the future?</h3>

<p>
Maybe. It depends on whether I find more features useful to what I
want to use the site for. If someone has a good idea and I find that
useful I might do it. 
</p>

<h3>How can I contact you?</h3>

<p>
  I'm on <a href="http://twitter.com">Twitter</a> as <a href="http://twitter.com/metajungle">@metajungle</a>
</p>

<p style="font-size: 0.8em; margin-top: 20px;">
  *No-one has actually asked these questions, so they are not
  frequently asked, but may still be helpful.
</p>

{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
<!--
$("#id_task").focus();

$(".btn-delete").click(function() {
    // hide the button just clicked 
    $(this).hide();

    // create the form to delete the label 
    var id = $(this).data('id');
    var source = $("#label-delete-confirm-template").html();
    var template = Handlebars.compile(source);
    var html = template({id: id});
    $(this).after(html);
  
    // register the cancel event 
    $('.btn-delete-cancel').click(function(e) {
        // remove the confirmation set of buttons 
        $(".btn-confirm").remove();
        // bring back the original button
       $(".btn-delete").show(); 
       e.stopPropagation();
    });
}); 
-->
</script>

<script id="label-delete-confirm-template" type="text/x-handlebars-template">
{% verbatim %}
<form action="/tasks/delete/{{id}}/" method="POST">
{% endverbatim %}
{% csrf_token %}
{% verbatim %}
<input type="submit" class="btn btn-danger btn-confirm btn-delete-confirm" value="Are you sure?" />
<button type="button" class="btn btn-default btn-confirm btn-delete-cancel">No</button>
</form>
{% endverbatim %}
</script>
{% endblock script %}

{% block contents %}
<form action="" method="POST" role="form">{% csrf_token %}

    <fieldset>
    {% for field in form %}
    
        <div class="form-group {% if field.errors %}has-error{% endif %}">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
        <ul class="list-unstyled">
          {% for error in field.errors %}
            <li>
            <span class="label label-danger">Error</span>
            <span class="text-danger">{{ error }}</span>
            </li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>

    {% endfor %}
    </fieldset>

    <span id="form-hidden-holder">
      {# default for labels #}
      <input type="hidden" name="labels" value="" />
      {# task id: for when a task is being edited #}
      {% if t_id %}
      <input type="hidden" name="t_id" value="{{ t_id }}" />
      {% endif %}
    </span>

    <button type="submit" name="save" class="btn btn-success">Save task</button>

    {# pass on the label ID of the active label before adding a task #}
    {% if get and get.orig_l_id %}
    <input type="hidden" name="orig_l_id" value="{{ get.orig_l_id }}" />
    {% else %}
    {% if orig_l_id %}
    <input type="hidden" name="orig_l_id" value="{{ orig_l_id }}" />
    {% endif %}
    {% endif %}

    <div class="pull-right">
      <button type="button" class="btn btn-danger btn-delete" data-id="{{ task.id }}">Delete task</button>
    </div>

</form>


{% endblock contents %}